# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-26 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170226_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='usr'),
        ),
    ]
